### ISSUE TITLE
Automated sanity checks of data

### ISSUE THREAD

**Issue by pescetti** [pescetti/COVID-19#2]
### Scope

Maps and charts at http://data.pescetti.it/2020-03-coronavirus-near-me/home.html are supposed to be updated automatically each time the upstream repo changes.

Data may have inconsistencies or be subject to misinterpretation, see https://github.com/pcm-dpc/COVID-19/issues/93 for an example. Since we want full automation (including website updates), we need to validate assumptions upon each refresh from the upstream repo.

### Tasks

- [ ] Define reasonable assumptions that can be checked (e.g.: the number of *total* cases in a given province/region never decreases; the total by province, including the "fake province", equals the region data)
- [ ] Write scripts to check them against one source (or better, write scripts that regenerate JSON and GeoJSON see #1 data from CSV)
- [ ] Ideally, integrate this in a CI system that can immediately flag problems in data

**Comment by pescetti** [comment]
Another reasonable assumption to add:

- The JSON file must contain more than one dataset (more than one date) see what happened in https://github.com/pcm-dpc/COVID-19/issues/171

**Comment by pescetti** [comment]
Another reasonable assumption that broke today:

- Region code and province code must be numbers, not strings. See https://github.com/pcm-dpc/COVID-19/issues/256

**Comment by pescetti** [comment]
Actually, we must simply validate that...

* All properties that are described as numbers are numbers and not strings. See https://github.com/pcm-dpc/COVID-19/issues/254

**Comment by bfabio** [comment]
@pescetti I published the API server here: https://covid-19.zland.org/, if you are interested.

I'm using a strongly typed language, so responses are guaranteeded to return consistent types (ie. the server won't even compile with unexpected data).
